# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  rules:
    no-unused-schemas: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  jsonSampleExpandLevel: 3
  expandResponses: "200,201"
  pathInMiddlePanel:  true
  theme:
    colors:
      primary:
        main: "#32329f"
