{
  "swagger": "2.0",
  "info": {
    "contact": {
      "email": "hello@biza.io",
      "name": "Biza.io",
      "url": "https://biza.io/"
    },
    "description": "This specification mirrors the definitions of the Australian Consumer Data Standards and is intended to deliver the Standards in OpenAPI 3 format with additional data specifications.\nThe source for this Redocs is available at [https://github.com/bizaio/dsb-standards](https://github.com/bizaio/dsb-standards).\nA downgraded Swagger 2 version of this document can be [downloaded here](http://bizaio.github.io/dsb-standards/swagger2.json).\n",
    "license": {
      "name": "GPL 3.0",
      "url": "https://opensource.org/licenses/GPL-3.0"
    },
    "title": "Consumer Data Standards (Biza.io Edition)",
    "version": "1.5.0"
  },
  "host": "data.holder.com.au",
  "basePath": "/cds-au/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/admin/metrics": {
      "get": {
        "security": [
          {
            "RegisterAuth": []
          }
        ],
        "tags": [
          "Admin",
          "Metrics"
        ],
        "description": "This end point allows the ACCC to obtain operational statistics from the Data Holder on the operation of their CDR compliant implementation. The statistics obtainable from this end point are determined by the non-functional requirements for the CDR regime.",
        "operationId": "getMetrics",
        "summary": "Get Metrics",
        "x-version": "1"
      }
    },
    "/admin/register/metadata": {
      "post": {
        "security": [
          {
            "RegisterAuth": []
          }
        ],
        "tags": [
          "Admin",
          "Register"
        ],
        "description": "Indicate that a critical update to the metadata for Accredited Data Recipients has been made and should be obtained",
        "operationId": "metadataUpdate",
        "summary": "Metadata Update",
        "x-version": "1"
      }
    },
    "/banking/accounts": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "tags": [
          "Accounts",
          "Banking"
        ],
        "description": "Obtain a list of accounts",
        "operationId": "listAccounts",
        "summary": "Get Accounts",
        "x-version": "1"
      }
    },
    "/banking/accounts/balances": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "tags": [
          "Balances",
          "Banking"
        ],
        "description": "Obtain balances for multiple, filtered accounts",
        "operationId": "listBalancesBulk",
        "summary": "Get Bulk Balances",
        "x-version": "1"
      },
      "post": {
        "security": [
          {
            "CDRAuth": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "tags": [
          "Balances",
          "Banking"
        ],
        "description": "Obtain balances for a specified list of accounts",
        "operationId": "listBalancesSpecificAccounts",
        "summary": "Get Balances For Specific Accounts",
        "x-version": "1"
      }
    },
    "/banking/accounts/direct-debits": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Direct Debits"
        ],
        "description": "Obtain direct debit authorisations for multiple, filtered accounts",
        "operationId": "listDirectDebitsBulk",
        "summary": "Get Bulk Direct Debits",
        "x-version": "1"
      },
      "post": {
        "security": [
          {
            "CDRAuth": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Direct Debits"
        ],
        "description": "Obtain direct debit authorisations for a specified list of accounts",
        "operationId": "listDirectDebitsSpecificAccounts",
        "summary": "Get Direct Debits For Specific Accounts",
        "x-version": "1"
      }
    },
    "/banking/accounts/{accountId}": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:accounts.detail:read"
            ]
          }
        ],
        "tags": [
          "Accounts",
          "Banking"
        ],
        "description": "Obtain detailed information on a single account",
        "operationId": "getAccountDetail",
        "summary": "Get Account Detail",
        "x-version": "1"
      }
    },
    "/banking/accounts/{accountId}/balance": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:accounts.basic:read"
            ]
          }
        ],
        "tags": [
          "Balances",
          "Banking"
        ],
        "description": "Obtain the balance for a single specified account",
        "operationId": "getBalance",
        "summary": "Get Account Balance",
        "x-version": "1"
      }
    },
    "/banking/accounts/{accountId}/direct-debits": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Direct Debits"
        ],
        "description": "Obtain direct debit authorisations for a specific account",
        "operationId": "listDirectDebits",
        "summary": "Get Direct Debits For Account",
        "x-version": "1"
      }
    },
    "/banking/accounts/{accountId}/payments/scheduled": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Scheduled Payments"
        ],
        "description": "Obtain scheduled, outgoing payments for a specific account",
        "operationId": "listScheduledPayments",
        "summary": "Get Scheduled Payments for Account",
        "x-version": "1"
      }
    },
    "/banking/accounts/{accountId}/transactions": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:transactions:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Transactions"
        ],
        "description": "Obtain transactions for a specific account.\n\nSome general notes that apply to all end points that retrieve transactions:\n\n- Where multiple transactions are returned, transactions should be ordered according to effective date in descending order\n- As the date and time for a transaction can alter depending on status and transaction type two separate date/times are included in the payload. There are still some scenarios where neither of these time stamps is available. F[...]",
        "operationId": "getTransactions",
        "summary": "Get Transactions For Account",
        "x-version": "1"
      }
    },
    "/banking/accounts/{accountId}/transactions/{transactionId}": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:transactions:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Transactions"
        ],
        "description": "Obtain detailed information on a transaction for a specific account",
        "operationId": "getTransactionDetail",
        "summary": "Get Transaction Detail",
        "x-version": "1"
      }
    },
    "/banking/payees": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:payees:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Payees"
        ],
        "description": "Obtain a list of pre-registered payees",
        "operationId": "listPayees",
        "summary": "Get Payees",
        "x-version": "1"
      }
    },
    "/banking/payees/{payeeId}": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:payees:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Payees"
        ],
        "description": "Obtain detailed information on a single payee. Note that the payee sub-structure should be selected to represent the payment destination only rather than any known characteristics of the payment recipient",
        "operationId": "getPayeeDetail",
        "summary": "Get Payee Detail",
        "x-version": "1"
      }
    },
    "/banking/payments/scheduled": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Scheduled Payments"
        ],
        "description": "Obtain scheduled payments for multiple, filtered accounts that are the source of funds for the payments",
        "operationId": "listScheduledPaymentsBulk",
        "summary": "Get Scheduled Payments Bulk",
        "x-version": "1"
      },
      "post": {
        "security": [
          {
            "CDRAuth": [
              "bank:regular_payments:read"
            ]
          }
        ],
        "tags": [
          "Banking",
          "Scheduled Payments"
        ],
        "description": "Obtain scheduled payments for a specified list of accounts",
        "operationId": "listScheduledPaymentsSpecificAccounts",
        "summary": "Get Scheduled Payments For Specific Accounts",
        "x-version": "1"
      }
    },
    "/banking/products": {
      "get": {
        "security": [],
        "tags": [
          "Banking",
          "Products"
        ],
        "description": "Obtain a list of products that are currently openly offered to the market\n\nNote that the results returned by this end point are expected to be ordered in descending order according to `lastUpdated`\n\n### Conventions\nIn the product reference payloads there are a number of recurring conventions that are explained here, in one place.\n\n#### Arrays Of Features\n\nIn the product detail payload there are a number of arrays articulating generic features, constraints, prices[...]",
        "operationId": "listProducts",
        "summary": "Get Products",
        "x-version": "3"
      }
    },
    "/banking/products/{productId}": {
      "get": {
        "security": [],
        "tags": [
          "Banking",
          "Products"
        ],
        "description": "Obtain detailed information on a single product offered openly to the market.\nNOTE: This version must be implemented by **February 2021**",
        "operationId": "getProductDetail",
        "summary": "Get Product Detail",
        "x-version": "3"
      }
    },
    "/common/customer": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "common:customer.basic:read"
            ]
          }
        ],
        "tags": [
          "Common",
          "Customer"
        ],
        "description": "Obtain basic information on the customer that has authorised the current session",
        "operationId": "getCustomer",
        "summary": "Get Customer",
        "x-version": "1"
      }
    },
    "/common/customer/detail": {
      "get": {
        "security": [
          {
            "CDRAuth": [
              "common:customer.detail:read"
            ]
          }
        ],
        "tags": [
          "Common",
          "Customer"
        ],
        "description": "Obtain detailed information on the authorised customer within the current session.",
        "operationId": "getCustomerDetail",
        "summary": "Get Customer Detail",
        "x-version": "1"
      }
    },
    "/discovery/outages": {
      "get": {
        "security": [],
        "tags": [
          "Common",
          "Discovery"
        ],
        "description": "Obtain a list of scheduled outages for the implementation",
        "operationId": "getOutages",
        "summary": "Get Outages",
        "x-version": "1"
      }
    },
    "/discovery/status": {
      "get": {
        "security": [],
        "tags": [
          "Common",
          "Discovery"
        ],
        "description": "Obtain a health check status for the implementation",
        "operationId": "getStatus",
        "summary": "Get Status",
        "x-version": "1"
      }
    }
  },
  "securityDefinitions": {
    "CDRAuth": {
      "authorizationUrl": "https://idp.holder.cdr/authorize",
      "flow": "accessCode",
      "scopes": {
        "bank:accounts.basic:read": "Basic Bank Account Data",
        "bank:accounts.detail:read": "Detailed Bank Account Data",
        "bank:payees:read": "Bank Payee Data",
        "bank:regular_payments:read": "Bank Regular Payments",
        "bank:transactions:read": "Bank Transaction Data",
        "common:customer.basic:read": "Basic Customer Data",
        "common:customer.detail:read": "Detailed Customer Data"
      },
      "tokenUrl": "https://idp.holder.cdr/token",
      "type": "oauth2"
    },
    "RegisterAuth": {
      "flow": "application",
      "scopes": {
        "cdr-register:bank:read": "CDR Bank Read Access"
      },
      "tokenUrl": "https://idp.cdr.register/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "description": "Admin APIs",
      "name": "Admin"
    },
    {
      "description": "Accounts Related APIs",
      "name": "Accounts"
    },
    {
      "description": "Account Balance Related APIs",
      "name": "Balances"
    },
    {
      "description": "Banking APIs",
      "name": "Banking"
    },
    {
      "description": "Common APIs",
      "name": "Common"
    },
    {
      "description": "Customer APIs",
      "name": "Customer"
    },
    {
      "description": "Discovery APIs",
      "name": "Discovery"
    },
    {
      "description": "Direct Debits APIs",
      "name": "Direct Debits"
    },
    {
      "description": "Metrics APIs",
      "name": "Metrics"
    },
    {
      "description": "Payee APIs",
      "name": "Payees"
    },
    {
      "description": "Products",
      "name": "Products"
    },
    {
      "description": "Register APIs",
      "name": "Register"
    },
    {
      "description": "Scheduled Payments APIs",
      "name": "Scheduled Payments"
    },
    {
      "description": "Transactions APIs",
      "name": "Transactions"
    },
    {
      "description": "# AdminAvailabilityMetrics\n\n## AdminAvailabilityMetricsV1\n<SchemaDefinition schemaRef=\"#/components/schemas/AdminAvailabilityMetricsV1\" />\n\n\n\n# AdminAverageResponseMetrics\n\n## AdminAverageResponseMetricsV1\n<SchemaDefinition schemaRef=\"#/components/schemas/AdminAverageResponseMetricsV1\" />\n\n\n\n# AdminErrorMetric\n\n## AdminErrorMetricV1\n<SchemaDefinition schemaRef=\"#/components/schemas/AdminErrorMetricV1\" />\n\n\n\n# AdminInvocationMetric\n\n## AdminInvoc[...]",
      "name": "Schemas"
    },
    {
      "description": "# EnumBankingAccountOpenStatus\n\n## EnumBankingAccountOpenStatusV1\n<SchemaDefinition schemaRef=\"#/components/schemas/EnumBankingAccountOpenStatusV1\" />\n\n\n\n# EnumBankingBillerCRNType\n\n## EnumBankingBillerCRNTypeV1\n<SchemaDefinition schemaRef=\"#/components/schemas/EnumBankingBillerCRNTypeV1\" />\n\n\n\n# EnumBankingDepositRateType\n\n## EnumBankingDepositRateTypeV1\n<SchemaDefinition schemaRef=\"#/components/schemas/EnumBankingDepositRateTypeV1\" />\n\n\n\n# EnumB[...]",
      "name": "Enumerations"
    },
    {
      "description": "# AdminAvailabilityMetrics\n\n## AdminAvailabilityMetricsV1\n<SchemaDefinition schemaRef=\"#/components/schemas/AdminAvailabilityMetricsV1\" />\n\n\n\n# AdminAverageResponseMetrics\n\n## AdminAverageResponseMetricsV1\n<SchemaDefinition schemaRef=\"#/components/schemas/AdminAverageResponseMetricsV1\" />\n\n\n\n# AdminErrorMetric\n\n## AdminErrorMetricV1\n<SchemaDefinition schemaRef=\"#/components/schemas/AdminErrorMetricV1\" />\n\n\n\n# AdminInvocationMetric\n\n## AdminInvoc[...]",
      "name": "Responses"
    }
  ],
  "x-components": {
  },
  "x-tagGroups": [
    {
      "tags": [
        "Accounts",
        "Balances",
        "Direct Debits",
        "Payees",
        "Products",
        "Scheduled Payments",
        "Transactions"
      ],
      "name": "Banking APIs"
    },
    {
      "tags": [
        "Customer",
        "Discovery"
      ],
      "name": "Common APIs"
    },
    {
      "tags": [
        "Register",
        "Metrics"
      ],
      "name": "Admin APIs"
    },
    {
      "tags": [
        "Schemas",
        "Enumerations",
        "Responses"
      ],
      "name": "Models"
    }
  ]
}
